name: release_docker

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: 'acgn0rg/onest'
  REGISTRY_USERNAME: 'acgn0rg'
  REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  RELEASE_PLATFORMS: 'linux/amd64,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/riscv64'

jobs:
  release_docker:
    name: Release Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Tag
        id: tag
        run: echo value=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'yarn'
          cache-dependency-path: web/yarn.lock

      - name: Build Frontend
        run: |
          cd web
          yarn install --frozen-lockfile
          yarn build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          logout: true
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.ci
          push: true
          build-args: OnestVersion=${{ steps.tag.outputs.value }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ env.RELEASE_PLATFORMS }}